# Generated by Django 2.2.7 on 2020-04-27 04:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oner',
            fields=[
                ('oner_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='media/')),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('panting_title', models.CharField(max_length=200)),
                ('panting_by', models.CharField(max_length=200)),
                ('panting_rate', models.IntegerField(default='free')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('pin_code', models.IntegerField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.CharField(choices=[('1', 'active'), ('0', 'dactive')], max_length=20)),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artwork.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artwork.User')),
            ],
        ),
    ]
