# Generated by Django 2.2.7 on 2020-04-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_user_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='panting_img',
            field=models.ImageField(default=' ', upload_to='media/'),
            preserve_default=False,
        ),
    ]
